[tools]
'asdf:neovim' = 'nightly'
fzf = 'latest'
rg = 'latest'
fd = 'latest'
navi = 'latest'

zls = 'latest'
black = 'latest'
prettier = 'latest'
stylua = 'latest'
'npm:pyright' = 'latest'
'npm:typescript-language-server' = 'latest'

pipx = 'latest'
'pipx:debugpy' = 'latest'
